/**
 * @iodigital-com/components-react
 * =============================
 * React wrapper package for io Digital Web Components.
 *
 * This file is the main package entry point.
 * The `components.ts` file is generated by Stencil's react-output-target
 * during `npm run build:components` — do not hand-edit it.
 *
 * Usage:
 *   import { IoButton, IoBadge, IoInput } from '@iodigital-com/components-react';
 */

// Global design tokens (app.css compiled by Stencil globalStyle).
// Importing here means any consumer of @iodigital-com/components-react
// automatically gets --io-* custom properties on :root without a separate CSS import.
import '@iodigital-com/components/global.css';

// Generated by @stencil/react-output-target — populated after first build
export * from './components';
