/**
 * @io-digital/components-react
 * =============================
 * React wrapper package for io Digital Web Components.
 *
 * This file is the main package entry point.
 * The `components.ts` file is generated by Stencil's react-output-target
 * during `npm run build:components` — do not hand-edit it.
 *
 * Usage:
 *   import { IoButton, IoBadge, IoInput } from '@io-digital/components-react';
 */

// Generated by @stencil/react-output-target — populated after first build
export * from './components';
