'use client';

import { SectionHeader, InlineCode, ApiTable, ReflectBadge, MutableBadge, EmptyNote } from '@/components/api/ApiPrimitives';

export default function IoTabPanelApiPage() {
  return (
    <div className="space-y-16">

      {/* ── Properties ───────────────────────────────────────────────────── */}
      <section id="properties" className="space-y-4">
        <SectionHeader
          title="Properties"
          description="All @Prop() declarations on the io-tab-panel Stencil component."
        />
        <ApiTable
          columns={[
            { label: 'Name', width: '200px' },
            { label: 'Type', width: '220px' },
            { label: 'Default', width: '100px' },
            { label: 'Description' },
          ]}
          rows={[
            [
              <span key="n">
                <InlineCode>label</InlineCode>
              </span>,
              <InlineCode key="t">string</InlineCode>,
              <span key="d" style={{ color: 'var(--io-text-secondary)', fontStyle: 'italic' }}>required</span>,
              <span key="desc">
                Text label for the corresponding tab button generated by io-tabs.
                Also used as the accessible name of the panel region when{' '}
                <InlineCode>labelledBy</InlineCode> is not set.
              </span>,
            ],
            [
              <span key="n">
                <InlineCode>hidden</InlineCode>
                <MutableBadge />
                <ReflectBadge />
              </span>,
              <InlineCode key="t">boolean</InlineCode>,
              <InlineCode key="d">false</InlineCode>,
              <span key="desc">
                When true, the panel is hidden (<InlineCode>display: none</InlineCode>).
                Set automatically by io-tabs based on the active tab index. Consumers may
                also set it directly when using the panel standalone.
              </span>,
            ],
            [
              <InlineCode key="n">labelledBy</InlineCode>,
              <InlineCode key="t">string | undefined</InlineCode>,
              <InlineCode key="d">undefined</InlineCode>,
              <span key="desc">
                ID of the tab button that controls this panel. Sets{' '}
                <InlineCode>aria-labelledby</InlineCode> on the panel element.
                Assigned automatically by io-tabs.
              </span>,
            ],
            [
              <InlineCode key="n">panelId</InlineCode>,
              <InlineCode key="t">string | undefined</InlineCode>,
              <InlineCode key="d">undefined</InlineCode>,
              <span key="desc">
                Explicit ID override for the panel element. If not set, a stable auto-generated
                ID is applied. io-tabs reads this ID for <InlineCode>aria-controls</InlineCode> wiring.
              </span>,
            ],
          ]}
        />
      </section>

      {/* ── Slots ────────────────────────────────────────────────────────── */}
      <section id="slots" className="space-y-4">
        <SectionHeader
          title="Slots"
          description="io-tab-panel uses a single default slot for panel content."
        />
        <ApiTable
          columns={[
            { label: 'Slot', width: '160px' },
            { label: 'Expected content' },
          ]}
          rows={[
            [
              <span key="s" style={{ color: 'var(--io-text-secondary)', fontStyle: 'italic' }}>default</span>,
              'Any content to display when this tab is active.',
            ],
          ]}
        />
      </section>

      {/* ── Events ───────────────────────────────────────────────────────── */}
      <section id="events" className="space-y-4">
        <SectionHeader
          title="Events"
          description="Custom events emitted by io-tab-panel."
        />
        <EmptyNote>
          <strong style={{ color: 'var(--io-text-primary)' }}>io-tab-panel emits no events.</strong>
          {' '}Panel visibility changes are driven by the parent io-tabs component.
        </EmptyNote>
      </section>

      {/* ── Methods ──────────────────────────────────────────────────────── */}
      <section id="methods" className="space-y-4">
        <SectionHeader
          title="Methods"
          description="Public @Method() calls exposed on the element reference."
        />
        <EmptyNote>
          <strong style={{ color: 'var(--io-text-primary)' }}>io-tab-panel exposes no public methods.</strong>
          {' '}Visibility is controlled via the <InlineCode>hidden</InlineCode> prop.
        </EmptyNote>
      </section>

    </div>
  );
}
