'use client';

import { PageHeader } from '@/components/layout/PageHeader';

export default function DevelopingReactPage() {
  return (
    <div className="space-y-10">
      <PageHeader
        title="React"
        description="Use io components in React 18+ applications via typed wrapper components generated by Stencil's React output target."
        tabs={[]}
      />

      {/* ── Installation ─────────────────────────────────────── */}
      <section className="space-y-4">
        <h2 className="text-lg font-bold" style={{ color: 'var(--io-text-primary)' }}>
          Installation
        </h2>
        <p className="text-sm" style={{ color: 'var(--io-text-secondary)', lineHeight: '1.6' }}>
          Install the core Web Components package together with the React wrapper. The wrapper re-exports components with
          full TypeScript types so your editor can autocomplete props and events.
        </p>
        <pre
          className="rounded-lg p-4 text-sm overflow-x-auto"
          style={{ background: 'var(--io-bg-raised)', border: '1px solid var(--io-border)', color: 'var(--io-text-secondary)' }}
        >
{`npm install @io-digital/components @io-digital/components-react`}
        </pre>
        <p className="text-sm" style={{ color: 'var(--io-text-secondary)', lineHeight: '1.6' }}>
          The React wrapper requires React 18 or later as a peer dependency — no extra configuration is needed for Vite,
          Create React App, or similar bundlers.
        </p>
      </section>

      {/* ── Registering the loader ─────────────────────────────── */}
      <section className="space-y-4">
        <h2 className="text-lg font-bold" style={{ color: 'var(--io-text-primary)' }}>
          Register the component loader
        </h2>
        <p className="text-sm" style={{ color: 'var(--io-text-secondary)', lineHeight: '1.6' }}>
          Call <code>defineCustomElements</code> once at your application entry point (e.g. <code>main.tsx</code>) to
          register the underlying Web Components with the browser. You only need to do this once.
        </p>
        <pre
          className="rounded-lg p-4 text-sm overflow-x-auto"
          style={{ background: 'var(--io-bg-raised)', border: '1px solid var(--io-border)', color: 'var(--io-text-secondary)' }}
        >
{`// main.tsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import { defineCustomElements } from '@io-digital/components/loader';
import App from './App';

defineCustomElements();

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);`}
        </pre>
      </section>

      {/* ── Basic usage ─────────────────────────────────────────── */}
      <section className="space-y-4">
        <h2 className="text-lg font-bold" style={{ color: 'var(--io-text-primary)' }}>
          Basic usage
        </h2>
        <p className="text-sm" style={{ color: 'var(--io-text-secondary)', lineHeight: '1.6' }}>
          Import wrapper components from <code>@io-digital/components-react</code>. They behave like ordinary React
          components — props are typed and work with JSX just as you would expect.
        </p>
        <pre
          className="rounded-lg p-4 text-sm overflow-x-auto"
          style={{ background: 'var(--io-bg-raised)', border: '1px solid var(--io-border)', color: 'var(--io-text-secondary)' }}
        >
{`import { IoButton, IoBadge, IoInput } from '@io-digital/components-react';

export function WelcomeBanner() {
  return (
    <div>
      <IoBadge color="green">New</IoBadge>
      <h1>Welcome to iO</h1>
      <IoInput label="Email address" type="email" name="email" required />
      <IoButton variant="solid" color="blue" size="md">
        Get started
      </IoButton>
    </div>
  );
}`}
        </pre>
      </section>

      {/* ── Event handling ──────────────────────────────────────── */}
      <section className="space-y-4">
        <h2 className="text-lg font-bold" style={{ color: 'var(--io-text-primary)' }}>
          Event handling
        </h2>
        <p className="text-sm" style={{ color: 'var(--io-text-secondary)', lineHeight: '1.6' }}>
          io components emit custom events prefixed with <code>io</code> (e.g. <code>change</code>,{' '}
          <code>click</code>). The React wrappers map these to camel-case <code>on*</code> props so they integrate with
          React's synthetic event model. Each handler receives a strongly-typed <code>CustomEvent</code>.
        </p>
        <pre
          className="rounded-lg p-4 text-sm overflow-x-auto"
          style={{ background: 'var(--io-bg-raised)', border: '1px solid var(--io-border)', color: 'var(--io-text-secondary)' }}
        >
{`import { useState } from 'react';
import { IoButton, IoInput, IoCheckbox } from '@io-digital/components-react';

export function ContactForm() {
  const [email, setEmail] = useState('');
  const [agreed, setAgreed] = useState(false);

  // change on IoInput — detail is the current string value
  const handleEmailChange = (e: CustomEvent<string>) => {
    setEmail(e.detail);
  };

  // change on IoCheckbox — detail is { checked: boolean }
  const handleCheckboxChange = (e: CustomEvent<{ checked: boolean }>) => {
    setAgreed(e.detail.checked);
  };

  // click on IoButton — detail is the native MouseEvent
  const handleSubmit = (e: CustomEvent<MouseEvent>) => {
    e.detail.preventDefault();
    console.log('Submitted:', { email, agreed });
  };

  return (
    <form>
      <IoInput
        label="Email address"
        type="email"
        name="email"
        value={email}
        onChange={handleEmailChange}
      />
      <IoCheckbox
        label="I agree to the terms"
        checked={agreed}
        onChange={handleCheckboxChange}
      />
      <IoButton
        variant="solid"
        color="blue"
        onClick={handleSubmit}
      >
        Submit
      </IoButton>
    </form>
  );
}`}
        </pre>

        <div
          className="rounded-lg p-5"
          style={{ background: 'var(--io-bg-raised)', border: '1px solid var(--io-border)' }}
        >
          <p className="font-semibold text-sm mb-2" style={{ color: 'var(--io-text-primary)' }}>
            Event map reference
          </p>
          <table className="w-full text-sm" style={{ color: 'var(--io-text-secondary)', borderCollapse: 'collapse' }}>
            <thead>
              <tr style={{ borderBottom: '1px solid var(--io-border)' }}>
                <th className="text-left py-2 pr-4 font-semibold" style={{ color: 'var(--io-text-primary)' }}>Component</th>
                <th className="text-left py-2 pr-4 font-semibold" style={{ color: 'var(--io-text-primary)' }}>Stencil event</th>
                <th className="text-left py-2 font-semibold" style={{ color: 'var(--io-text-primary)' }}>React prop</th>
              </tr>
            </thead>
            <tbody>
              {[
                ['IoButton', 'click', 'onClick'],
                ['IoInput', 'change / input / focus / blur', 'onChange / onInput / onFocus / onBlur'],
                ['IoCheckbox', 'change', 'onChange'],
                ['IoSelect', 'change / focus / blur', 'onChange / onFocus / onBlur'],
                ['IoTabs', 'change', 'onChange'],
                ['IoTag', 'toggle / remove', 'onToggle / onRemove'],
              ].map(([component, stencil, react]) => (
                <tr key={component} style={{ borderBottom: '1px solid var(--io-border)' }}>
                  <td className="py-2 pr-4"><code>{component}</code></td>
                  <td className="py-2 pr-4"><code>{stencil}</code></td>
                  <td className="py-2"><code>{react}</code></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* ── Typed props ─────────────────────────────────────────── */}
      <section className="space-y-4">
        <h2 className="text-lg font-bold" style={{ color: 'var(--io-text-primary)' }}>
          Typed props and autocompletion
        </h2>
        <p className="text-sm" style={{ color: 'var(--io-text-secondary)', lineHeight: '1.6' }}>
          Every wrapper component ships with TypeScript prop types generated directly from the Stencil component
          definitions. Your IDE will autocomplete valid values for union props such as <code>variant</code>,{' '}
          <code>color</code>, and <code>size</code>.
        </p>
        <pre
          className="rounded-lg p-4 text-sm overflow-x-auto"
          style={{ background: 'var(--io-bg-raised)', border: '1px solid var(--io-border)', color: 'var(--io-text-secondary)' }}
        >
{`// TypeScript will catch invalid prop values at compile time
<IoButton variant="solid" color="blue" size="md">Primary</IoButton>
<IoButton variant="ghost" color="red" size="sm">Danger</IoButton>
<IoButton variant="link" color="blue">Back</IoButton>

// Hover over any prop in your editor to see its accepted type
// e.g. color: 'blue' | 'red' | 'green' | 'purple' | ...`}
        </pre>
      </section>

      {/* ── SSR caveats ─────────────────────────────────────────── */}
      <section className="space-y-4">
        <h2 className="text-lg font-bold" style={{ color: 'var(--io-text-primary)' }}>
          SSR caveats
        </h2>
        <p className="text-sm" style={{ color: 'var(--io-text-secondary)', lineHeight: '1.6' }}>
          io components are Web Components backed by Stencil. They require browser APIs (<code>customElements</code>,{' '}
          <code>HTMLElement</code>) that are not available in Node environments. When rendering server-side — for example
          in Next.js App Router — keep these rules in mind:
        </p>
        <ul className="text-sm space-y-2 list-disc pl-5" style={{ color: 'var(--io-text-secondary)', lineHeight: '1.6' }}>
          <li>
            Wrap any file that imports from <code>@io-digital/components-react</code> with the{' '}
            <code>'use client'</code> directive (Next.js) or equivalent boundary.
          </li>
          <li>
            Call <code>defineCustomElements</code> only inside a browser check or a client-side effect:
          </li>
        </ul>
        <pre
          className="rounded-lg p-4 text-sm overflow-x-auto"
          style={{ background: 'var(--io-bg-raised)', border: '1px solid var(--io-border)', color: 'var(--io-text-secondary)' }}
        >
{`// Safe loader registration in SSR environments
import { useEffect } from 'react';

export function ComponentLoader() {
  useEffect(() => {
    import('@io-digital/components/loader').then(({ defineCustomElements }) => {
      defineCustomElements();
    });
  }, []);

  return null;
}`}
        </pre>
        <ul className="text-sm space-y-2 list-disc pl-5" style={{ color: 'var(--io-text-secondary)', lineHeight: '1.6' }}>
          <li>
            Stencil applies hydration via <code>scoped</code> or <code>shadow</code> CSS encapsulation — no additional
            hydration adaptor is required for React 18 streaming.
          </li>
        </ul>
      </section>

      {/* ── Testing caveats ─────────────────────────────────────── */}
      <section className="space-y-4">
        <h2 className="text-lg font-bold" style={{ color: 'var(--io-text-primary)' }}>
          Testing with Jest / Vitest
        </h2>
        <p className="text-sm" style={{ color: 'var(--io-text-secondary)', lineHeight: '1.6' }}>
          Jest and Vitest run in a Node environment, so custom elements are not defined by default. Follow these steps to
          keep your component tests reliable:
        </p>
        <ul className="text-sm space-y-2 list-disc pl-5" style={{ color: 'var(--io-text-secondary)', lineHeight: '1.6' }}>
          <li>
            Use <strong>jsdom</strong> as the test environment — it provides a partial DOM API that Stencil can work
            with.
          </li>
          <li>
            Call <code>defineCustomElements</code> inside a <code>beforeAll</code> / <code>beforeEach</code> block or a
            global setup file so components are registered before your assertions run.
          </li>
          <li>
            Query custom elements by tag name (<code>io-button</code>) or use accessible queries (role, label) via
            Testing Library — do not rely on shadow-DOM internals.
          </li>
          <li>
            Dispatch events manually with <code>CustomEvent</code> and check side-effects in your component state rather
            than inspecting shadow DOM nodes.
          </li>
        </ul>
        <pre
          className="rounded-lg p-4 text-sm overflow-x-auto"
          style={{ background: 'var(--io-bg-raised)', border: '1px solid var(--io-border)', color: 'var(--io-text-secondary)' }}
        >
{`// vitest.setup.ts
import { defineCustomElements } from '@io-digital/components/loader';
beforeAll(() => defineCustomElements());

// ContactForm.test.tsx
import { render, screen } from '@testing-library/react';
import { ContactForm } from './ContactForm';

test('updates email on change', async () => {
  render(<ContactForm />);
  const input = document.querySelector('io-input')!;

  // Dispatch the custom event the wrapper listens to
  input.dispatchEvent(
    new CustomEvent('change', { detail: 'test@example.com', bubbles: true }),
  );

  // Assert your React state or visible output changed
  expect(await screen.findByDisplayValue('test@example.com')).toBeInTheDocument();
});`}
        </pre>
      </section>

      {/* ── Troubleshooting ─────────────────────────────────────── */}
      <section className="space-y-4">
        <h2 className="text-lg font-bold" style={{ color: 'var(--io-text-primary)' }}>
          Troubleshooting
        </h2>
        <div className="space-y-4">
          {[
            {
              problem: 'Components render as unknown HTML elements',
              fix: 'Ensure defineCustomElements() has been called before the first render. Check your entry point (main.tsx / index.tsx) and confirm the import path is @io-digital/components/loader.',
            },
            {
              problem: 'Event handlers never fire',
              fix: 'Verify you are using the on* prop form (e.g. onChange) on the wrapper, not addEventListener on the host element. Also confirm the event name casing matches the Stencil definition.',
            },
            {
              problem: 'TypeScript cannot find module @io-digital/components-react',
              fix: 'Run npm install to ensure both packages are installed, then check that your tsconfig paths do not exclude node_modules. If using a monorepo, confirm workspace links are resolved.',
            },
            {
              problem: 'Styles do not apply / component looks unstyled',
              fix: 'Import the global stylesheet once in your entry point: import "@io-digital/components/dist/io/io.css". This file ships the design tokens and base resets.',
            },
            {
              problem: 'hydration mismatch warnings in Next.js',
              fix: 'Mark the file with "use client" at the top and lazy-import defineCustomElements inside a useEffect so it only runs in the browser.',
            },
          ].map(({ problem, fix }) => (
            <div
              key={problem}
              className="rounded-lg p-5"
              style={{ background: 'var(--io-bg-raised)', border: '1px solid var(--io-border)' }}
            >
              <p className="font-semibold text-sm mb-1" style={{ color: 'var(--io-text-primary)' }}>
                {problem}
              </p>
              <p className="text-sm" style={{ color: 'var(--io-text-secondary)', lineHeight: '1.6' }}>
                {fix}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* ── Next actions ────────────────────────────────────────── */}
      <section className="space-y-4">
        <h2 className="text-lg font-bold" style={{ color: 'var(--io-text-primary)' }}>
          Next steps
        </h2>
        <ul className="text-sm space-y-2 list-disc pl-5" style={{ color: 'var(--io-text-secondary)', lineHeight: '1.6' }}>
          <li>Browse the component library to explore available components and their props.</li>
          <li>Check the design tokens reference to apply consistent spacing, color, and typography.</li>
          <li>Read the accessibility guide — io components ship with ARIA roles and keyboard behaviour built in, but your
            integration layer must not break them by suppressing focus or overriding roles.</li>
          <li>For Next.js App Router projects, see the dedicated Next.js integration guide.</li>
        </ul>
      </section>
    </div>
  );
}
