/**
 * MIGRATION STUB — io-tooltip uses `shadow: false` (light DOM / attribute-bridge pattern).
 * This file is NOT imported by io-tooltip.tsx and its styles are NOT applied in production.
 * The actual tooltip overlay is styled via `.io-tooltip-overlay` in src/global/app.css.
 *
 * This file is intentionally kept as documentation for the shadow DOM migration path.
 * If io-tooltip is ever converted to shadow DOM, this function becomes the styles entrypoint.
 * The spec tests in io-tooltip.spec.ts validate token contracts in this migration stub.
 *
 * Do NOT edit this file expecting visual changes — edit app.css instead.
 */
export function getTooltipStyles(): string {
  return `
    :host {
      display: inline-block;
    }

    .tooltip {
      position: fixed;
      z-index: var(--io-z-tooltip);
      background: var(--io-bg-card);
      border: 1px solid var(--io-border);
      border-radius: var(--io-border-radius-sm);
      box-shadow: var(--io-shadow-md);
      color: var(--io-text-primary);
      font-family: var(--io-font-primary);
      font-size: var(--io-font-size-xs);
      line-height: var(--io-line-height-normal);
      padding: var(--io-space-2) var(--io-space-3);
      width: max-content;
      max-width: 240px;
      white-space: normal;
      word-break: break-word;
      /* pointer-events intentionally omitted — tooltip must be hoverable (WCAG 1.4.13) */
      opacity: 0;
      visibility: hidden;
      transition:
        opacity var(--io-motion-overlay-fade),
        visibility var(--io-motion-overlay-fade);
    }

    .tooltip--visible {
      opacity: 1;
      visibility: visible;
    }

    @media (prefers-reduced-motion: reduce) {
      .tooltip {
        transition: none;
      }
    }
  `;
}
