/**
 * MIGRATION STUB — io-tooltip uses `shadow: false` (light DOM / attribute-bridge pattern).
 * This file is NOT imported by io-tooltip.tsx and its styles are NOT applied in production.
 * The actual tooltip overlay is styled via `.io-tooltip-overlay` in src/global/app.css.
 *
 * This file is intentionally kept as documentation for the shadow DOM migration path.
 * If io-tooltip is ever converted to shadow DOM, this function becomes the styles entrypoint.
 * The spec tests in io-tooltip.spec.ts validate token contracts in this migration stub.
 *
 * Token API (these tokens are defined in app.css and pass through the Shadow DOM boundary):
 *   --io-tooltip-bg            Background colour — dark theme default.
 *   --io-tooltip-color         Text colour — dark theme default.
 *   --io-tooltip-max-width     Max width of the tooltip panel. Default: 20rem.
 *   --io-tooltip-show-delay    Delay before showing on hover/focus. Default: 500ms.
 *   --io-tooltip-hide-delay    Delay before hiding after pointer leaves. Default: 150ms.
 *
 * Do NOT edit this file expecting visual changes — edit app.css instead.
 */
export function getTooltipStyles(): string {
  return `
    :host {
      display: inline-block;
    }

    .tooltip {
      position: fixed;
      z-index: var(--io-z-tooltip);
      background: var(--io-tooltip-bg, var(--io-color-grey-6, #242424));
      border: 1px solid transparent;
      border-radius: var(--io-border-radius-sm);
      box-shadow: var(--io-shadow-md);
      color: var(--io-tooltip-color, var(--io-color-white, #ffffff));
      font-family: var(--io-font-primary);
      font-size: var(--io-font-size-xs);
      line-height: var(--io-line-height-normal);
      padding: var(--io-space-2) var(--io-space-3);
      width: max-content;
      max-width: var(--io-tooltip-max-width, 20rem);
      white-space: normal;
      word-break: break-word;
      /* pointer-events intentionally omitted — tooltip must be hoverable (WCAG 1.4.13) */
      opacity: 0;
      visibility: hidden;
      transition:
        opacity var(--io-motion-overlay-fade),
        visibility var(--io-motion-overlay-fade);
    }

    .tooltip--light {
      background: var(--io-tooltip-light-bg, var(--io-color-white, #ffffff));
      color: var(--io-tooltip-light-color, var(--io-text-primary));
      border-color: var(--io-border);
    }

    .tooltip--visible {
      opacity: 1;
      visibility: visible;
    }

    @media (prefers-reduced-motion: reduce) {
      .tooltip {
        transition: none;
      }
    }
  `;
}
