import type { Metadata } from 'next';
import Link from 'next/link';

import { PageHeader } from '@/components/layout/PageHeader';

export const metadata: Metadata = {
  title: 'FAQ — io Design System',
  description: 'Answers to common questions about installation, framework integration, accessibility, versioning, and contributing to io Design System.',
  openGraph: {
    title: 'FAQ — io Design System',
    description: 'Answers to common questions about installation, framework integration, accessibility, versioning, and contributing to io Design System.',
    type: 'website',
  },
};

type FaqItem = {
  heading: string;
  answer: string;
};

type FaqCategory = {
  title: string;
  items: FaqItem[];
};

const FAQ_CATEGORIES: FaqCategory[] = [
  {
    title: 'Installation',
    items: [
      {
        heading: 'Which npm packages do I need?',
        answer:
          'Install @iodigital-com/components for the core Stencil Web Components and design tokens. Add the framework-specific wrapper package for your stack: @iodigital-com/components-react, @iodigital-com/components-vue, or @iodigital-com/components-angular. All packages are published on the public npm registry.',
      },
      {
        heading: 'How do I load the component styles?',
        answer:
          'Add a link tag pointing to the io-components.css stylesheet — or, in Next.js, copy the file to your public folder and reference it in layout.tsx. The CSS file contains all --io-* design tokens and base component styles.',
      },
    ],
  },
  {
    title: 'Framework integration',
    items: [
      {
        heading: 'How do I use the components in Next.js?',
        answer:
          'Load io-components.esm.js as a beforeInteractive script in your root layout, then import the CSS stylesheet. Components are standard HTML custom elements and render in both Server and Client Components. See the Next.js integration guide under Developing for step-by-step instructions.',
      },
      {
        heading: 'How do I use the components in React?',
        answer:
          'Install @iodigital-com/components-react and import named wrappers like IoButton, IoModal. The React wrappers are auto-generated by Stencil and provide full TypeScript prop types and event bindings. See the React integration guide under Developing.',
      },
      {
        heading: 'Can I use io Design System outside of io Digital products?',
        answer:
          'The packages are published publicly on npm and can be used in any project, but the design language is specifically crafted for io Digital brand guidelines.',
      },
    ],
  },
  {
    title: 'Accessibility',
    items: [
      {
        heading: 'Are the components WCAG AA compliant?',
        answer:
          'Yes. All interactive components target WCAG 2.1 AA conformance — keyboard navigation, focus management, colour contrast, and ARIA semantics are built in. Run the axe-core integration tests (npm run test:a11y) to verify conformance in your environment.',
      },
      {
        heading: 'Which browsers are supported?',
        answer:
          'All evergreen browsers: Chrome, Firefox, Safari, and Edge. Web Components (Custom Elements v1 + Shadow DOM v1) are natively supported in all modern browsers with no polyfills required.',
      },
    ],
  },
  {
    title: 'Versioning and upgrades',
    items: [
      {
        heading: 'How do I upgrade between major versions?',
        answer:
          'Breaking changes are documented in the Changelog with migration notes. Check the Changelog page before upgrading — any breaking change entry includes the affected prop or event and the replacement API.',
      },
      {
        heading: 'How do I know if a component changed in a release?',
        answer:
          'Each release block in the Changelog lists Added, Changed, Fixed, and Deprecated entries per package. Breaking changes are highlighted separately. Subscribe to the GitHub repository to receive release notifications.',
      },
    ],
  },
  {
    title: 'Contributing',
    items: [
      {
        heading: 'How do I report a bug or request a feature?',
        answer:
          'Open a GitHub issue using the appropriate template — Bug Report, Feature Request, or Implementation Question. Include reproduction steps, expected behaviour, and your environment details. See the Support page for links.',
      },
      {
        heading: 'Can I contribute a new component?',
        answer:
          'Yes. New components require a GitHub issue for tracking, a design token audit, full WCAG AA accessibility support, and passing Vitest tests. Follow the contributing guidelines in the repository root before opening a pull request.',
      },
    ],
  },
];

export default function FaqPage() {
  return (
    <div className="space-y-10">
      <PageHeader
        title="FAQ"
        description="Answers to common questions about installation, framework integration, accessibility, versioning, and contributing."
        tabs={[]}
      />

      <div className="space-y-10">
        {FAQ_CATEGORIES.map((category) => {
          const categoryId = `faq-${category.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')}`;
          return (
          <section key={category.title} className="space-y-3" aria-labelledby={categoryId}>
            <h2
              id={categoryId}
              className="text-base font-semibold"
              style={{ color: 'var(--io-text-primary)' }}
            >
              {category.title}
            </h2>

            <div className="space-y-2">
              {category.items.map((item, i) => (
                <io-accordion key={`${categoryId}-${i}`} heading={item.heading}>
                  <p className="text-sm leading-relaxed" style={{ color: 'var(--io-text-secondary)' }}>
                    {item.answer}
                  </p>
                </io-accordion>
              ))}
            </div>
          </section>
          );
        })}
      </div>

      <p className="text-sm" style={{ color: 'var(--io-text-secondary)' }}>
        Can't find your answer?{' '}
        <Link href="/help/support" className="font-semibold" style={{ color: 'var(--io-color-primary)' }}>
          Visit the Support page
        </Link>{' '}
        to open a bug report or feature request.
      </p>
    </div>
  );
}
