/**
 * parseChangelog
 * ==============
 * Pure function — parses either Keep-a-Changelog or Changesets-generated
 * markdown into a typed Release[] array. Called from a Next.js Server
 * Component at build time (output: 'export').
 *
 * Supported formats:
 *
 * Keep-a-Changelog:
 *   ## [Version] — YYYY-MM-DD          (versioned release)
 *   ## [Unreleased]                     (unreleased block)
 *   ### Added / Changed / Fixed / Deprecated
 *   - bullet item text
 *
 * Changesets (auto-generated by @changesets/cli):
 *   ## 1.4.0                            (bare semver, no brackets, no date)
 *   ### Minor Changes / Patch Changes / Major Changes
 *   - abc1234: feat(scope): description (hash-prefixed bullets)
 *
 * Multiple ### subsections of the same type within one release are merged.
 * Changesets sections map: Minor Changes → Added, Patch Changes → Fixed,
 * Major Changes → Changed (breakingChanges bucket when "Breaking" in subtitle).
 */

export type ReleaseSection = 'Added' | 'Changed' | 'Fixed' | 'Deprecated';

export type Release = {
  version: string;
  date?: string;
  summary: string;
  sections: Partial<Record<ReleaseSection, string[]>>;
  breakingChanges?: string[];
  migrationNotes?: string[];
};

// Matches both "[1.0.0] — 2026-06-02" and bare "1.4.0" (changesets format)
const VERSION_RE =
  /^(?:\[(?<version>[^\]]+)\](?:\s*[—–-]+\s*(?<date>\d{4}-\d{2}-\d{2}))?|(?<bareVersion>\d+\.\d+\.\d+[\w.-]*))/;

// Matches Keep-a-Changelog and Changesets section headers
const SECTION_RE =
  /^### (?<type>Added|Changed|Fixed|Deprecated|Minor Changes|Patch Changes|Major Changes)(?:\s*[—–-].*)?$/;

// Maps changesets section names to ReleaseSection enum values
const SECTION_NAME_MAP: Record<string, ReleaseSection> = {
  Added: 'Added',
  Changed: 'Changed',
  Fixed: 'Fixed',
  Deprecated: 'Deprecated',
  'Minor Changes': 'Added',
  'Patch Changes': 'Fixed',
  'Major Changes': 'Changed',
};

const BULLET_RE = /^[-*]\s+(.+)$/;
const BOLD_HEADING_RE = /^\*\*(.+?)\*\*[:\s]*$/;
// Strip 7–40 char hex commit hash prefix added by changesets: "abc1234: "
const HASH_PREFIX_RE = /^[0-9a-f]{7,40}:\s*/;

const SECTION_ORDER: ReleaseSection[] = ['Added', 'Changed', 'Fixed', 'Deprecated'];

export function parseChangelog(raw: string): Release[] {
  if (!raw.trim()) return [];

  const releases: Release[] = [];

  // Split on lines that start a new version block ("## ")
  const blocks = raw.split(/\n(?=## )/);

  for (const block of blocks) {
    const lines = block.split('\n');

    // Find the version header line
    const headerLine = lines.find((l) => l.startsWith('## '));
    if (!headerLine) continue;

    const versionMatch = VERSION_RE.exec(headerLine.replace(/^## /, ''));
    if (!versionMatch?.groups) continue;

    const version = versionMatch.groups.version ?? versionMatch.groups.bareVersion;
    if (!version) continue;
    const { date } = versionMatch.groups;

    // Extract summary: the first non-empty, non-section, non-separator line after the header
    let summary = '';
    let pastHeader = false;
    for (const line of lines) {
      if (!pastHeader) {
        if (line.startsWith('## ')) {
          pastHeader = true;
        }
        continue;
      }
      const trimmed = line.trim();
      if (!trimmed || trimmed === '---' || trimmed.startsWith('### ') || trimmed.startsWith('**')) {
        continue;
      }
      if (!trimmed.startsWith('-') && !trimmed.startsWith('*') && !trimmed.startsWith('[')) {
        summary = trimmed;
        break;
      }
    }

    if (!summary) {
      summary =
        version === 'Unreleased'
          ? 'Changes queued for the next published release.'
          : `Release ${version}.`;
    }

    // Extract sections
    const sections: Partial<Record<ReleaseSection, string[]>> = {};
    const breakingChanges: string[] = [];

    let currentSection: ReleaseSection | null = null;
    let isBreaking = false;

    for (const line of lines) {
      const sectionMatch = SECTION_RE.exec(line.trim());
      if (sectionMatch?.groups) {
        const rawType = sectionMatch.groups.type;
        currentSection = SECTION_NAME_MAP[rawType] ?? (rawType as ReleaseSection);
        // Detect "Breaking" in the optional subtitle or in the section name itself
        isBreaking = line.toLowerCase().includes('breaking');
        continue;
      }

      if (!currentSection) continue;

      const bulletMatch = BULLET_RE.exec(line.trim());
      if (bulletMatch) {
        // Strip markdown bold markers then changesets commit-hash prefix
        const text = bulletMatch[1]
          .replace(/\*\*([^*]+)\*\*/g, '$1')
          .replace(HASH_PREFIX_RE, '')
          .trim();
        if (isBreaking) {
          breakingChanges.push(text);
        } else {
          if (!sections[currentSection]) sections[currentSection] = [];
          sections[currentSection]!.push(text);
        }
      } else {
        // Capture standalone bold lines as sub-section headings (e.g. **15 Web Components:**)
        const boldMatch = BOLD_HEADING_RE.exec(line.trim());
        if (boldMatch) {
          const heading = boldMatch[1].trim();
          if (!sections[currentSection]) sections[currentSection] = [];
          sections[currentSection]!.push(heading);
        }
      }
    }

    const release: Release = {
      version,
      ...(date ? { date } : {}),
      summary,
      sections,
    };

    if (breakingChanges.length > 0) release.breakingChanges = breakingChanges;

    releases.push(release);
  }

  // Unreleased first, then by version string descending
  return releases.sort((a, b) => {
    if (a.version === 'Unreleased') return -1;
    if (b.version === 'Unreleased') return 1;
    return b.version.localeCompare(a.version, undefined, { numeric: true });
  });
}

export { SECTION_ORDER };
