/* eslint-disable */
/* tslint:disable */
/**
 * Auto-generated by scripts/sync-stencil-assets.cjs from
 * io-components/dist/types/components.d.ts.
 * Do not edit manually.
 */

import type * as React from 'react';
import type { JSX as StencilJSX } from '../../../io-components/dist/types/components';

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
  'io-accordion': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoAccordionElement>, HTMLIoAccordionElement> & Partial<StencilJSX.IoAccordion>;
  'io-ai-tag': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoAiTagElement>, HTMLIoAiTagElement> & Partial<StencilJSX.IoAiTag>;
  'io-app-shell': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoAppShellElement>, HTMLIoAppShellElement> & Partial<StencilJSX.IoAppShell>;
  'io-avatar': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoAvatarElement>, HTMLIoAvatarElement> & Partial<StencilJSX.IoAvatar>;
  'io-badge': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoBadgeElement>, HTMLIoBadgeElement> & Partial<StencilJSX.IoBadge>;
  'io-banner': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoBannerElement>, HTMLIoBannerElement> & Partial<StencilJSX.IoBanner>;
  'io-breadcrumb': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoBreadcrumbElement>, HTMLIoBreadcrumbElement> & Partial<StencilJSX.IoBreadcrumb>;
  'io-breadcrumb-item': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoBreadcrumbItemElement>, HTMLIoBreadcrumbItemElement> & Partial<StencilJSX.IoBreadcrumbItem>;
  'io-button': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoButtonElement>, HTMLIoButtonElement> & Partial<StencilJSX.IoButton>;
  'io-button-group': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoButtonGroupElement>, HTMLIoButtonGroupElement> & Partial<StencilJSX.IoButtonGroup>;
  'io-button-pure': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoButtonPureElement>, HTMLIoButtonPureElement> & Partial<StencilJSX.IoButtonPure>;
  'io-button-tile': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoButtonTileElement>, HTMLIoButtonTileElement> & Partial<StencilJSX.IoButtonTile>;
  'io-carousel': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoCarouselElement>, HTMLIoCarouselElement> & Partial<StencilJSX.IoCarousel>;
  'io-checkbox': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoCheckboxElement>, HTMLIoCheckboxElement> & Partial<StencilJSX.IoCheckbox>;
  'io-checkbox-group': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoCheckboxGroupElement>, HTMLIoCheckboxGroupElement> & Partial<StencilJSX.IoCheckboxGroup>;
  'io-divider': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoDividerElement>, HTMLIoDividerElement> & Partial<StencilJSX.IoDivider>;
  'io-drawer': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoDrawerElement>, HTMLIoDrawerElement> & Partial<StencilJSX.IoDrawer>;
  'io-fieldset': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoFieldsetElement>, HTMLIoFieldsetElement> & Partial<StencilJSX.IoFieldset>;
  'io-flag': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoFlagElement>, HTMLIoFlagElement> & Partial<StencilJSX.IoFlag>;
  'io-flyout': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoFlyoutElement>, HTMLIoFlyoutElement> & Partial<StencilJSX.IoFlyout>;
  'io-form-field': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoFormFieldElement>, HTMLIoFormFieldElement> & Partial<StencilJSX.IoFormField>;
  'io-grid': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoGridElement>, HTMLIoGridElement> & Partial<StencilJSX.IoGrid>;
  'io-grid-item': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoGridItemElement>, HTMLIoGridItemElement> & Partial<StencilJSX.IoGridItem>;
  'io-heading': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoHeadingElement>, HTMLIoHeadingElement> & Partial<StencilJSX.IoHeading>;
  'io-icon': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoIconElement>, HTMLIoIconElement> & Partial<StencilJSX.IoIcon>;
  'io-inline-notification': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoInlineNotificationElement>, HTMLIoInlineNotificationElement> & Partial<StencilJSX.IoInlineNotification>;
  'io-input': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoInputElement>, HTMLIoInputElement> & Partial<StencilJSX.IoInput>;
  'io-input-date': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoInputDateElement>, HTMLIoInputDateElement> & Partial<StencilJSX.IoInputDate>;
  'io-input-password': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoInputPasswordElement>, HTMLIoInputPasswordElement> & Partial<StencilJSX.IoInputPassword>;
  'io-input-search': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoInputSearchElement>, HTMLIoInputSearchElement> & Partial<StencilJSX.IoInputSearch>;
  'io-link': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoLinkElement>, HTMLIoLinkElement> & Partial<StencilJSX.IoLink>;
  'io-link-pure': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoLinkPureElement>, HTMLIoLinkPureElement> & Partial<StencilJSX.IoLinkPure>;
  'io-link-tile': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoLinkTileElement>, HTMLIoLinkTileElement> & Partial<StencilJSX.IoLinkTile>;
  'io-modal': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoModalElement>, HTMLIoModalElement> & Partial<StencilJSX.IoModal>;
  'io-multi-select': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoMultiSelectElement>, HTMLIoMultiSelectElement> & Partial<StencilJSX.IoMultiSelect>;
  'io-optgroup': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoOptgroupElement>, HTMLIoOptgroupElement> & Partial<StencilJSX.IoOptgroup>;
  'io-option': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoOptionElement>, HTMLIoOptionElement> & Partial<StencilJSX.IoOption>;
  'io-pagination': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoPaginationElement>, HTMLIoPaginationElement> & Partial<StencilJSX.IoPagination>;
  'io-pin-code': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoPinCodeElement>, HTMLIoPinCodeElement> & Partial<StencilJSX.IoPinCode>;
  'io-popover': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoPopoverElement>, HTMLIoPopoverElement> & Partial<StencilJSX.IoPopover>;
  'io-product-tile': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoProductTileElement>, HTMLIoProductTileElement> & Partial<StencilJSX.IoProductTile>;
  'io-progress': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoProgressElement>, HTMLIoProgressElement> & Partial<StencilJSX.IoProgress>;
  'io-radio': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoRadioElement>, HTMLIoRadioElement> & Partial<StencilJSX.IoRadio>;
  'io-radio-group': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoRadioGroupElement>, HTMLIoRadioGroupElement> & Partial<StencilJSX.IoRadioGroup>;
  'io-scroller': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoScrollerElement>, HTMLIoScrollerElement> & Partial<StencilJSX.IoScroller>;
  'io-segment': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoSegmentElement>, HTMLIoSegmentElement> & Partial<StencilJSX.IoSegment>;
  'io-segmented-control': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoSegmentedControlElement>, HTMLIoSegmentedControlElement> & Partial<StencilJSX.IoSegmentedControl>;
  'io-select': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoSelectElement>, HTMLIoSelectElement> & Partial<StencilJSX.IoSelect>;
  'io-sheet': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoSheetElement>, HTMLIoSheetElement> & Partial<StencilJSX.IoSheet>;
  'io-spinner': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoSpinnerElement>, HTMLIoSpinnerElement> & Partial<StencilJSX.IoSpinner>;
  'io-step': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoStepElement>, HTMLIoStepElement> & Partial<StencilJSX.IoStep>;
  'io-stepper': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoStepperElement>, HTMLIoStepperElement> & Partial<StencilJSX.IoStepper>;
  'io-switch': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoSwitchElement>, HTMLIoSwitchElement> & Partial<StencilJSX.IoSwitch>;
  'io-tab-panel': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoTabPanelElement>, HTMLIoTabPanelElement> & Partial<StencilJSX.IoTabPanel>;
  'io-table': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoTableElement>, HTMLIoTableElement> & Partial<StencilJSX.IoTable>;
  'io-table-body': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoTableBodyElement>, HTMLIoTableBodyElement> & Partial<StencilJSX.IoTableBody>;
  'io-table-body-cell': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoTableBodyCellElement>, HTMLIoTableBodyCellElement> & Partial<StencilJSX.IoTableBodyCell>;
  'io-table-body-row': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoTableBodyRowElement>, HTMLIoTableBodyRowElement> & Partial<StencilJSX.IoTableBodyRow>;
  'io-table-head': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoTableHeadElement>, HTMLIoTableHeadElement> & Partial<StencilJSX.IoTableHead>;
  'io-table-head-cell': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoTableHeadCellElement>, HTMLIoTableHeadCellElement> & Partial<StencilJSX.IoTableHeadCell>;
  'io-table-head-row': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoTableHeadRowElement>, HTMLIoTableHeadRowElement> & Partial<StencilJSX.IoTableHeadRow>;
  'io-tabs': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoTabsElement>, HTMLIoTabsElement> & Partial<StencilJSX.IoTabs>;
  'io-tabs-bar': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoTabsBarElement>, HTMLIoTabsBarElement> & Partial<StencilJSX.IoTabsBar>;
  'io-tag': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoTagElement>, HTMLIoTagElement> & Partial<StencilJSX.IoTag>;
  'io-tag-dismissible': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoTagDismissibleElement>, HTMLIoTagDismissibleElement> & Partial<StencilJSX.IoTagDismissible>;
  'io-text': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoTextElement>, HTMLIoTextElement> & Partial<StencilJSX.IoText>;
  'io-text-list': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoTextListElement>, HTMLIoTextListElement> & Partial<StencilJSX.IoTextList>;
  'io-text-list-item': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoTextListItemElement>, HTMLIoTextListItemElement> & Partial<StencilJSX.IoTextListItem>;
  'io-textarea': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoTextareaElement>, HTMLIoTextareaElement> & Partial<StencilJSX.IoTextarea>;
  'io-toast': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoToastElement>, HTMLIoToastElement> & Partial<StencilJSX.IoToast>;
  'io-toast-item': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoToastItemElement>, HTMLIoToastItemElement> & Partial<StencilJSX.IoToastItem>;
  'io-tooltip': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoTooltipElement>, HTMLIoTooltipElement> & Partial<StencilJSX.IoTooltip>;
  'io-wordmark': React.DetailedHTMLProps<React.HTMLAttributes<HTMLIoWordmarkElement>, HTMLIoWordmarkElement> & Partial<StencilJSX.IoWordmark>;
    }
  }
}
