/**
 * Auto-generated by scripts/sync-stencil-assets.cjs from
 * io-components/dist/types/components.d.ts.
 * Do not edit manually.
 */

export type IoTagNames =
  | 'io-accordion'
  | 'io-badge'
  | 'io-button'
  | 'io-button-group'
  | 'io-carousel'
  | 'io-checkbox'
  | 'io-divider'
  | 'io-input'
  | 'io-link'
  | 'io-modal'
  | 'io-optgroup'
  | 'io-option'
  | 'io-pagination'
  | 'io-radio'
  | 'io-select'
  | 'io-spinner'
  | 'io-tabs'
  | 'io-tag'
  | 'io-textarea'
  | 'io-toast'
  | 'io-toast-item'
  | 'io-tooltip';
