import type { PropDefinition } from '@/models/propDefinition';
import type { Story } from '@/models/story';

export const tabPanelStory: Story<'io-tab-panel'> = {
  state: {
    properties: {
      label: 'Overview',
      hidden: false,
    },
  },
  generator: ({ properties } = {}) => [
    {
      tag: 'io-tab-panel' as const,
      properties: {
        label: (properties?.label as string) ?? 'Overview',
        hidden: (properties?.hidden as boolean) ?? false,
      },
      children: ['Tab panel content goes here.'],
    },
  ],
};

export const tabPanelStoryDefault: Story<'io-tab-panel'> = {
  state: { properties: { label: 'Overview' } },
  generator: () => [
    {
      tag: 'io-tab-panel' as const,
      properties: { label: 'Overview' },
      children: ['This is the Overview tab panel.'],
    },
  ],
};

export const tabPanelStoryHidden: Story<'io-tab-panel'> = {
  state: { properties: { label: 'Details', hidden: true } },
  generator: () => [
    {
      tag: 'io-tab-panel' as const,
      properties: { label: 'Details', hidden: true },
      children: ['This panel is hidden.'],
    },
  ],
};

export const tabPanelPropDefinitions: PropDefinition[] = [
  {
    name: 'label',
    type: 'string',
    defaultValue: 'Overview',
    description: 'Label for the tab button generated by io-tabs, and accessible name of the panel region.',
  },
  {
    name: 'hidden',
    type: 'boolean',
    defaultValue: false,
    description: 'When true, the panel is hidden (display: none). Set automatically by io-tabs.',
  },
  {
    name: 'labelledBy',
    type: 'string',
    defaultValue: '',
    description: 'ID of the tab button that controls this panel. Assigned automatically by io-tabs.',
  },
  {
    name: 'panelId',
    type: 'string',
    defaultValue: '',
    description: 'Explicit ID override for the panel element. If not set, a stable auto-generated ID is applied.',
  },
];
